import './css/style.css'

import { Inter } from 'next/font/google'

import Header from '@/components/ui/header' 

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app', 
}
